if (typeof window === 'undefined') {
  require('source-map-support').install()
}
// require('./define')
// require('./inject')
// require('./serialize')
// require('./traversal')
// require('./references')
// require('./compute')
// require('./props')
// require('./get')
// require('./iterators')
// require('./references')
// require('./once')
// require('./async')
// require('./set')
// require('./remove')
// require('./context')
// require('./on')
// require('./subscribe')
require('./types')
